name: Unittest

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Test on ${{ matrix.gover }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gover:
          - "1.13"
          - "1.14"
          - "1.15"
          - "1.16"
          - "1.17"
          - "1.18"
          - "1.19"
          - "1.20"
          - "1.21"
        lintVer:
          - v1.52.0
          - v1.52.2
    env:
      GOVER: ${{ matrix.gover }}
      GOLANGCILINT_VER: ${{ matrix.lintVer }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GOVER }}

    - name: Tidy
      run: go mod tidy

    - name: Test
      run: go test -count=1 -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Cover
      uses: codecov/codecov-action@v3

    - name: Lint
      uses: golangci/golangci-lint-action@v3.4.0
      with:
        version: ${{ env.GOLANGCILINT_VER }}
        skip-cache: true
